decoration {
    dim_inactive = true
    dim_strength = 0.17
}
windowrule {
    name = turbo-pascal-inactive-opacity
    match:tag = default-opacity
    match:focus = false
    match:fullscreen = false
    opacity = 0.97 override
}
bezier = turboPascalSettle, 0.25, 0.75, 0.5, 1
animation = fadeSwitch, 1, 2.75, turboPascalSettle
animation = fadeDim, 1, 2.75, turboPascalSettle
